In [1]:
import main as tools
final_dateframe = tools.all_years_merge()
print(final_dateframe.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   trnOpDate        9000 non-null   int64
 1   車站代碼             9000 non-null   int64
 2   gateInComingCnt  9000 non-null   int64
 3   gateOutGoingCnt  9000 non-null   int64
 4   車站名稱             433 non-null    object
 5   車站地址             433 non-null    object
dtypes: int64(4), object(2)
memory usage: 422.0+ KB
None

In [2]:
final_dateframe.head()

   trnOpDate  車站代碼  gateInComingCnt  gateOutGoingCnt 車站名稱           車站地址
0   20190102   920             2346             2731   八堵  基隆市暖暖區八堵路142號
1   20190102  7302             1492             1437  NaN            NaN
2   20190102  7378             1516             1750  NaN            NaN
3   20190102  7384             1494             1618  NaN            NaN
4   20190103  7344             1467             1477  NaN            NaN

In [ ]:
import pandas as pd

final_dateframe['trnOpDate'] = pd.to_datetime(
    final_dateframe['trnOpDate'].astype(str),
    format='%Y%m%d'
)
final_dateframe.head()

   trnOpDate  車站代碼  gateInComingCnt  gateOutGoingCnt 車站名稱           車站地址
0 2019-01-02   920             2346             2731   八堵  基隆市暖暖區八堵路142號
1 2019-01-02  7302             1492             1437  NaN            NaN
2 2019-01-02  7378             1516             1750  NaN            NaN
3 2019-01-02  7384             1494             1618  NaN            NaN
4 2019-01-03  7344             1467             1477  NaN            NaN

In [10]:
final_dateframe.groupby('車站名稱', as_index=False).agg({
    'gateInComingCnt': 'mean',
    'gateOutGoingCnt': 'mean'
})

  車站名稱  gateInComingCnt  gateOutGoingCnt
0   七堵      2521.340426      2647.148936
1   三坑      2545.322581      2649.838710
2   八堵      2539.650000      2671.400000
3  八斗子      1719.026316      1732.210526
4  四腳亭      1604.700000      1629.633333
5   基隆      2598.888889      2647.944444
6   暖暖      1621.444444      1665.444444
7  海科館      1576.560976      1604.756098
8   瑞芳      1587.531250      1644.531250
9   百福      2553.872727      2602.145455

In [13]:
# 如何groupby多欄位,依據年份gropby
final_dateframe['year'] = final_dateframe['trnOpDate'].dt.year
df1 = final_dateframe.groupby(['year','車站名稱'])[
    ['gateInComingCnt','gateOutGoingCnt']].sum()    
df1

           gateInComingCnt  gateOutGoingCnt
year 車站名稱
2019 七堵              18532            20073
     三坑              13288            14205
     八堵              34831            36766
     八斗子              3694             3862
     四腳亭              7536             7726
     基隆              18009            18310
     暖暖               9755             9930
     海科館             15301            15747
     瑞芳              12831            13726
     百福              26266            26870
2020 七堵              18607            19380
     三坑               7073             7720
     八堵              24822            26221
     八斗子              7140             6626
     四腳亭              4734             4884
     基隆              19164            18920
     暖暖              10904            11536
     海科館             10255            10244
     瑞芳               7624             8230
     百福              19486            20948
2021 七堵              16738            16913
     三坑               8120             8057
     八堵              21518            22665
     八斗子              5030             5299
     四腳亭             11349            11422
     基隆              22941            23757
     暖暖              11261            11186
     海科館             11628            11639
     瑞芳               7973             8414
     百福              19386            19955
2022 七堵              25655            27034
     三坑              17856            18484
     八堵              25921            26374
     八斗子             14087            14287
     四腳亭              6183             6653
     基隆              20408            21106
     暖暖               6552             6837
     海科館             10507            10516
     瑞芳               7764             7773
     百福              21315            21251
2023 七堵              18712            19765
     三坑              18569            18985
     八堵              22622            24885
     八斗子             16386            16341
     四腳亭             12866            12861
     基隆              30076            31335
     暖暖              12701            13250
     海科館             11206            11659
     瑞芳               8804             8788
     百福              26590            28149
2024 七堵              20259            21251
     三坑              13999            14694
     八堵              22665            23373
     八斗子             18986            19409
     四腳亭              5473             5343
     基隆              29742            29561
     暖暖              21792            22206
     海科館              5742             5990
     瑞芳               5805             5694
     百福              27420            25945

In [14]:
df2 = df1.unstack(level="year")
df2.head()

     gateInComingCnt                                    gateOutGoingCnt  \
year            2019   2020   2021   2022   2023   2024            2019
車站名稱
七堵             18532  18607  16738  25655  18712  20259           20073
三坑             13288   7073   8120  17856  18569  13999           14205
八堵             34831  24822  21518  25921  22622  22665           36766
八斗子             3694   7140   5030  14087  16386  18986            3862
四腳亭             7536   4734  11349   6183  12866   5473            7726


year   2020   2021   2022   2023   2024
車站名稱
七堵    19380  16913  27034  19765  21251
三坑     7720   8057  18484  18985  14694
八堵    26221  22665  26374  24885  23373
八斗子    6626   5299  14287  16341  19409
四腳亭    4884  11422   6653  12861   5343