In [8]:
import os

#取得目前工作目錄
current_working_directory = os.getcwd()
print("目前工作目錄:", current_working_directory)

#取得該目錄下'data'資料夾內'每日各站進出人數2020.csv'檔案的完整路徑
data_file_path = os.path.join(current_working_directory, 'data', '每日各站進出站人數2020.csv')
print("資料檔案完整路徑:", data_file_path)

目前工作目錄: /Users/golden/Desktop/AI分析/Python/Test_AI/Lesson19
資料檔案完整路徑: /Users/golden/Desktop/AI分析/Python/Test_AI/Lesson19/data/每日各站進出站人數2020.csv

In [9]:
import pandas as pd
data = pd.read_csv(data_file_path)
data1 = data.rename(columns={"trnOpDate":"乘車日期",
                             "staCode":"車站代碼",
                             "gateInComingCnt":"進站人數",
                             "gateOutGoingCnt":"出站人數"})
data1.head()

       乘車日期  車站代碼  進站人數  出站人數
0  20200101   914  2501  2654
1  20200101   969  2518  2604
2  20200101  7304  1554  1635
3  20200101  7349  1576  1678
4  20200101  7371  1546  1719

In [14]:
#取得目前工作目錄
current_working_directory = os.getcwd()

#取得該目錄下'data'資料夾內'台鐵車站資訊.csv'檔案的完整路徑
data_file_path = os.path.join(current_working_directory, 'data', '台鐵車站資訊.csv')
station_data = pd.read_csv(data_file_path)
station_data1= station_data[["stationCode","stationName","stationAddrTw"]]
station_data2= station_data1.rename(columns={"stationCode":"車站代碼","stationName":"車站名稱","stationAddrTw":"車站地址"})
station_data2.head()

   車站代碼 車站名稱               車站地址
0   900   基隆        基隆市仁愛區港西街5號
1   910   三坑   基隆市仁愛區德厚里龍安街206號
2   920   八堵      基隆市暖暖區八堵路142號
3   930   七堵     基隆市七堵區長興里東新街2號
4   940   百福  基隆市七堵區堵南里明德三路1之1號

In [15]:
#自訂function, 讀取絕對位置,輸入檔案名稱, 回傳完整路徑
def get_data_file_path(file_name):
    current_working_directory = os.getcwd()
    data_file_path = os.path.join(current_working_directory, 'data', file_name)
    return data_file_path

#使用自訂function讀取'台鐵車站資訊.csv'檔案
station_file_path = get_data_file_path('台鐵車站資訊.csv')
station_data = pd.read_csv(station_file_path)
station_data1= station_data[["stationCode","stationName","stationAddrTw"]]
station_data2= station_data1.rename(columns={"stationCode":"車站代碼","stationName":"車站名稱","stationAddrTw":"車站地址"})
station_data2.head()

   車站代碼 車站名稱               車站地址
0   900   基隆        基隆市仁愛區港西街5號
1   910   三坑   基隆市仁愛區德厚里龍安街206號
2   920   八堵      基隆市暖暖區八堵路142號
3   930   七堵     基隆市七堵區長興里東新街2號
4   940   百福  基隆市七堵區堵南里明德三路1之1號

In [16]:
# data1內的‘車站代碼’與station_data2內的‘車站代碼’做合併
merged_data = pd.merge(data1, station_data2, on="車站代碼", how="left")
merged_data.head()

       乘車日期  車站代碼  進站人數  出站人數 車站名稱 車站地址
0  20200101   914  2501  2654  NaN  NaN
1  20200101   969  2518  2604  NaN  NaN
2  20200101  7304  1554  1635  NaN  NaN
3  20200101  7349  1576  1678  NaN  NaN
4  20200101  7371  1546  1719  NaN  NaN

In [9]:
#取得該目錄下的data資料夾的路徑
data_directory = os.path.join(current_working_directory, 'data')
#列出data資料夾內所有檔案
files_in_data_directory = os.listdir(data_directory)
files_in_data_directory

['每日各站進出站人數2021.csv',
 '每日各站進出站人數2020.csv',
 '每日各站進出站人數2022.csv',
 '每日各站進出站人數2023.csv',
 '每日各站進出站人數2024.csv',
 '每日各站進出站人數2019.csv',
 '台鐵車站資訊.csv']

In [11]:
#取得該目錄下的data資料夾的路徑
data_directory = os.path.join(current_working_directory, 'data')

#列出data資料夾內所有包含'每日各站進出站人數'的檔案
files_in_data_directory = [f for f in os.listdir(data_directory) if '每日各站進出站人數' in f]
files_in_data_directory

['每日各站進出站人數2021.csv',
 '每日各站進出站人數2020.csv',
 '每日各站進出站人數2022.csv',
 '每日各站進出站人數2023.csv',
 '每日各站進出站人數2024.csv',
 '每日各站進出站人數2019.csv']

In [3]:
import os
import pandas as pd
from pandas import DataFrame

#自訂function, 讀取絕對位置,輸入檔案名稱, 回傳完整路徑
def get_data_file_path(file_name):
    current_working_directory = os.getcwd()
    data_file_path = os.path.join(current_working_directory, 'data', file_name)
    return data_file_path

def merge_two_table(filename: str) -> DataFrame:
    file_path = get_data_file_path(filename)
    data = pd.read_csv(file_path)

    data1 = data.rename(columns={
        "trnOpDate": "乘車日期",
        "staCode": "車站代碼",
        "gateInComingCnt": "進站人數",
        "gateOutGoingCnt": "出站人數"
    })

    station_path = get_data_file_path("台鐵車站資訊.csv")
    station_data = pd.read_csv(station_path)

    station_data1 = station_data[
        ["stationCode", "stationName", "stationAddrTw"]
    ]

    station_data2 = station_data1.rename(columns={
        "stationCode": "車站代碼",
        "stationName": "車站名稱",
        "stationAddrTw": "車站地址"
    })

    merged_data = pd.merge(
        data1,
        station_data2,
        on="車站代碼",
        how="left"
    )

    return merged_data


merge_table = merge_two_table("每日各站進出站人數2020.csv")
merge_table.head()

       乘車日期  車站代碼  進站人數  出站人數 車站名稱 車站地址
0  20200101   914  2501  2654  NaN  NaN
1  20200101   969  2518  2604  NaN  NaN
2  20200101  7304  1554  1635  NaN  NaN
3  20200101  7349  1576  1678  NaN  NaN
4  20200101  7371  1546  1719  NaN  NaN

In [4]:
#以下使用chatgpt重構後的程式碼

from __future__ import annotations

from pathlib import Path
from typing import Final, Optional

import pandas as pd


# ====== 常數設定（集中管理，避免散落各處）======
DATA_DIR: Final[str] = "data"

RIDERSHIP_RENAME_MAP: Final[dict[str, str]] = {
    "trnOpDate": "乘車日期",
    "staCode": "車站代碼",
    "gateInComingCnt": "進站人數",
    "gateOutGoingCnt": "出站人數",
}

STATION_KEEP_COLS: Final[list[str]] = ["stationCode", "stationName", "stationAddrTw"]

STATION_RENAME_MAP: Final[dict[str, str]] = {
    "stationCode": "車站代碼",
    "stationName": "車站名稱",
    "stationAddrTw": "車站地址",
}


# ====== 小工具函式 ======
def get_data_file_path(file_name: str, base_dir: Optional[Path] = None) -> Path:
    """
    回傳 data 資料夾底下指定檔案的完整路徑。

    Parameters
    ----------
    file_name : str
        檔名，例如 "每日各站進出站人數2020.csv"
    base_dir : Path | None
        專案根目錄（預設為目前工作目錄 Path.cwd()）

    Returns
    -------
    Path
        完整檔案路徑 (Path 物件)
    """
    base = base_dir or Path.cwd()
    return base / DATA_DIR / file_name


def _require_columns(df: pd.DataFrame, required: list[str], df_name: str) -> None:
    """
    檢查 DataFrame 是否包含必要欄位；缺少就丟出清楚的錯誤。
    """
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"{df_name} 缺少必要欄位：{missing}\n目前欄位：{list(df.columns)}")


# ====== 主功能 ======
def merge_two_table(
    ridership_filename: str,
    station_filename: str = "台鐵車站資訊.csv",
    *,
    parse_date: bool = True,
    base_dir: Optional[Path] = None,
) -> pd.DataFrame:
    """
    讀取每日進出站人數與台鐵車站資訊，並以「車站代碼」進行合併（left join）。

    合併後欄位（主要）：
    - 乘車日期 / 車站代碼 / 進站人數 / 出站人數 / 車站名稱 / 車站地址

    Parameters
    ----------
    ridership_filename : str
        每日進出站資料檔名，例如 "每日各站進出站人數2020.csv"
    station_filename : str
        車站資訊檔名，預設 "台鐵車站資訊.csv"
    parse_date : bool
        是否把「乘車日期」轉成 datetime（預設 True）
    base_dir : Path | None
        專案根目錄（預設使用 Path.cwd()）

    Returns
    -------
    pd.DataFrame
        合併後的 DataFrame
    """
    # --- 讀取每日進出站資料 ---
    ridership_path = get_data_file_path(ridership_filename, base_dir=base_dir)
    if not ridership_path.exists():
        raise FileNotFoundError(f"找不到檔案：{ridership_path}")

    ridership_df = pd.read_csv(ridership_path)
    _require_columns(ridership_df, list(RIDERSHIP_RENAME_MAP.keys()), "每日進出站資料")

    # 重新命名欄位
    ridership_df = ridership_df.rename(columns=RIDERSHIP_RENAME_MAP)

    # 乘車日期：常見格式是 yyyymmdd（例如 20200101）
    if parse_date and "乘車日期" in ridership_df.columns:
        ridership_df["乘車日期"] = pd.to_datetime(
            ridership_df["乘車日期"].astype(str),
            format="%Y%m%d",
            errors="coerce",
        )

    # --- 讀取車站資料 ---
    station_path = get_data_file_path(station_filename, base_dir=base_dir)
    if not station_path.exists():
        raise FileNotFoundError(f"找不到檔案：{station_path}")

    station_df = pd.read_csv(station_path)
    _require_columns(station_df, STATION_KEEP_COLS, "車站資訊資料")

    # 只保留需要欄位，並重新命名
    station_df = station_df[STATION_KEEP_COLS].rename(columns=STATION_RENAME_MAP)

    # --- 合併（left join 保留每日進出站的所有資料） ---
    merged_df = pd.merge(
        ridership_df,
        station_df,
        on="車站代碼",
        how="left",
        validate="many_to_one",  # 每個車站代碼在 station_df 應該只對應一筆（有助抓錯）
    )

    return merged_df


# ====== 使用範例 ======
merge_table = merge_two_table("每日各站進出站人數2020.csv")
print(merge_table.head())

        乘車日期  車站代碼  進站人數  出站人數 車站名稱 車站地址
0 2020-01-01   914  2501  2654  NaN  NaN
1 2020-01-01   969  2518  2604  NaN  NaN
2 2020-01-01  7304  1554  1635  NaN  NaN
3 2020-01-01  7349  1576  1678  NaN  NaN
4 2020-01-01  7371  1546  1719  NaN  NaN