In [2]:
import main as tools

final_dateframe = tools.all_years_merge()
print(final_dateframe.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   trnOpDate        9000 non-null   int64
 1   車站代碼             9000 non-null   int64
 2   gateInComingCnt  9000 non-null   int64
 3   gateOutGoingCnt  9000 non-null   int64
 4   車站名稱             433 non-null    object
 5   車站地址             433 non-null    object
dtypes: int64(4), object(2)
memory usage: 422.0+ KB
None

In [ ]:
# groupby
import numpy as np
import pandas as pd

df = pd.DataFrame({
    'key1': ['a', 'a', 'b', 'b', 'a'],
    'key2': ['one', 'two', 'one', 'two', 'one'],
    'data1': np.random.randn(5),
    'data2': np.random.randn(5)
})

  key1 key2     data1     data2
0    a  one -0.131924 -0.224725
1    a  two -1.003772 -0.593934
2    b  one  1.117025 -1.844087
3    b  two  0.634311  0.358091
4    a  one  0.128151  0.745145

In [10]:
df.groupby('key1')["data1"].mean()
df.groupby('key1')[["data1","data2"]].mean()  # 多欄位
df.groupby(['key1','key2']).mean()  # 多欄位當 key

df1 = df.groupby(['key1','key2']).mean()
df1

              data1     data2
key1 key2
a    one  -0.001886  0.260210
     two  -1.003772 -0.593934
b    one   1.117025 -1.844087
     two   0.634311  0.358091

In [17]:
# 3個索引的series, 變成長的資料

df2 = df1.stack()
df2.index.names = ['key1','key2','data']
df2

key1  key2  data
a     one   data1   -0.001886
            data2    0.260210
      two   data1   -1.003772
            data2   -0.593934
b     one   data1    1.117025
            data2   -1.844087
      two   data1    0.634311
            data2    0.358091
dtype: float64

In [20]:
df3 = df2.unstack(level=['data','key1']) #變回寬的資料, as 樞紐分析
df3

data     data1     data2     data1     data2
key1         a         a         b         b
key2
one  -0.001886  0.260210  1.117025 -1.844087
two  -1.003772 -0.593934  0.634311  0.358091

In [21]:
df3['data1']

key1         a         b
key2
one  -0.001886  1.117025
two  -1.003772  0.634311