In [ ]:
import pandas as pd

world_df = pd.read_csv('world.csv')
print(world_df.columns)
print(world_df.info())

In [2]:
world_df1 = world_df[['洲名','國家', '日期','總確診數','新增確診數','總人口數','總死亡數']]
world_df1

            洲名           國家          日期      總確診數  新增確診數        總人口數    總死亡數
0         Asia  Afghanistan  2020-01-01       NaN    NaN  40578847.0     NaN
1         Asia  Afghanistan  2020-01-02       NaN    NaN  40578847.0     NaN
2         Asia  Afghanistan  2020-01-03       NaN    NaN  40578847.0     NaN
3         Asia  Afghanistan  2020-01-04       0.0    0.0  40578847.0     0.0
4         Asia  Afghanistan  2020-01-05       0.0    0.0  40578847.0     0.0
...        ...          ...         ...       ...    ...         ...     ...
548746  Africa     Zimbabwe  2025-11-19  266436.0    0.0  16069061.0  5740.0
548747  Africa     Zimbabwe  2025-11-20  266436.0    0.0  16069061.0  5740.0
548748  Africa     Zimbabwe  2025-11-21  266436.0    0.0  16069061.0  5740.0
548749  Africa     Zimbabwe  2025-11-22  266436.0    0.0  16069061.0  5740.0
548750  Africa     Zimbabwe  2025-11-23  266436.0    0.0  16069061.0  5740.0

[548751 rows x 7 columns]

In [3]:
mask_taiwan = world_df1["國家"] == "Taiwan"
taiwan_data = world_df1[mask_taiwan]
taiwan_data

          洲名      國家          日期  總確診數  新增確診數        總人口數  總死亡數
474651  Asia  Taiwan  2020-01-01   NaN    NaN  23420107.0   NaN
474652  Asia  Taiwan  2020-01-02   NaN    NaN  23420107.0   NaN
474653  Asia  Taiwan  2020-01-03   NaN    NaN  23420107.0   NaN
474654  Asia  Taiwan  2020-01-04   NaN    NaN  23420107.0   NaN
474655  Asia  Taiwan  2020-01-05   NaN    NaN  23420107.0   NaN
...      ...     ...         ...   ...    ...         ...   ...
476056  Asia  Taiwan  2025-08-31   NaN    NaN  23420107.0   NaN
476057  Asia  Taiwan  2025-09-30   NaN    NaN  23420107.0   NaN
476058  Asia  Taiwan  2025-10-31   NaN    NaN  23420107.0   NaN
476059  Asia  Taiwan  2025-11-30   NaN    NaN  23420107.0   NaN
476060  Asia  Taiwan  2025-12-31   NaN    NaN  23420107.0   NaN

[1410 rows x 7 columns]

In [4]:
#使用DataFrame的Query方法
taiwan_date_query = world_df1.query("國家 == 'Taiwan'")
taiwan_date_query

          洲名      國家          日期  總確診數  新增確診數        總人口數  總死亡數
474651  Asia  Taiwan  2020-01-01   NaN    NaN  23420107.0   NaN
474652  Asia  Taiwan  2020-01-02   NaN    NaN  23420107.0   NaN
474653  Asia  Taiwan  2020-01-03   NaN    NaN  23420107.0   NaN
474654  Asia  Taiwan  2020-01-04   NaN    NaN  23420107.0   NaN
474655  Asia  Taiwan  2020-01-05   NaN    NaN  23420107.0   NaN
...      ...     ...         ...   ...    ...         ...   ...
476056  Asia  Taiwan  2025-08-31   NaN    NaN  23420107.0   NaN
476057  Asia  Taiwan  2025-09-30   NaN    NaN  23420107.0   NaN
476058  Asia  Taiwan  2025-10-31   NaN    NaN  23420107.0   NaN
476059  Asia  Taiwan  2025-11-30   NaN    NaN  23420107.0   NaN
476060  Asia  Taiwan  2025-12-31   NaN    NaN  23420107.0   NaN

[1410 rows x 7 columns]

In [8]:
taiwan_max = taiwan_data["新增確診數"].max()
taiwan_max
taiwan_max_row = taiwan_data.query("新增確診數 == @taiwan_max")
taiwan_max_row

Empty DataFrame
Columns: [洲名, 國家, 日期, 總確診數, 新增確診數, 總人口數, 總死亡數]
Index: []