In [2]:
import pandas as pd

tips = pd.read_csv('tips.csv')
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  122 non-null    float64
 1   tip         122 non-null    float64
 2   smoker      122 non-null    object
 3   day         122 non-null    object
 4   time        122 non-null    object
 5   size        122 non-null    int64
dtypes: float64(2), int64(1), object(3)
memory usage: 5.8+ KB

In [5]:
#改變tips的欄位名稱
tips.columns = ['總票價', '小費', '是否吸菸', '日期', '時間', '人數']   
tips

       總票價    小費 是否吸菸    日期      時間  人數
0    21.85  3.86  Yes  Thur  Dinner   2
1    47.78  1.99  Yes   Mon   Lunch   1
2    37.94  3.05   No   Wed  Dinner   2
3    31.94  4.84  Yes   Mon  Dinner   3
4    12.02  8.36  Yes   Fri  Dinner   2
..     ...   ...  ...   ...     ...  ..
117  13.40  2.59  Yes   Mon  Dinner   3
118  45.17  9.46  Yes   Tue   Lunch   1
119  29.27  9.59   No   Sat  Dinner   5
120  41.33  9.23   No   Sun   Lunch   1
121  45.32  4.33   No   Mon  Dinner   2

[122 rows x 6 columns]

In [7]:
#欄位重新排列
tips = tips[['日期', '時間', '是否吸菸', '人數', '總票價', '小費']]

#新鄒一個欄位 小費佔總票價比例
tips['小費佔比'] = tips['小費'] / tips['總票價']
tips

       日期      時間 是否吸菸  人數    總票價    小費      小費佔比
0    Thur  Dinner  Yes   2  21.85  3.86  0.176659
1     Mon   Lunch  Yes   1  47.78  1.99  0.041649
2     Wed  Dinner   No   2  37.94  3.05  0.080390
3     Mon  Dinner  Yes   3  31.94  4.84  0.151534
4     Fri  Dinner  Yes   2  12.02  8.36  0.695507
..    ...     ...  ...  ..    ...   ...       ...
117   Mon  Dinner  Yes   3  13.40  2.59  0.193284
118   Tue   Lunch  Yes   1  45.17  9.46  0.209431
119   Sat  Dinner   No   5  29.27  9.59  0.327639
120   Sun   Lunch   No   1  41.33  9.23  0.223324
121   Mon  Dinner   No   2  45.32  4.33  0.095543

[122 rows x 7 columns]

In [8]:
# 依照日期,建立一個群組
tips_grouped = tips.groupby('日期')
len(tips_grouped)

7