In [1]:
import pandas as pd

df1 = pd.read_csv('tips.csv')
df1.columns = ['總票價','小費','吸煙者','日期','時間','人數']
df1['小費比例'] = df1['小費']/df1['總票價']
df1

       總票價    小費  吸煙者    日期      時間  人數      小費比例
0    21.85  3.86  Yes  Thur  Dinner   2  0.176659
1    47.78  1.99  Yes   Mon   Lunch   1  0.041649
2    37.94  3.05   No   Wed  Dinner   2  0.080390
3    31.94  4.84  Yes   Mon  Dinner   3  0.151534
4    12.02  8.36  Yes   Fri  Dinner   2  0.695507
..     ...   ...  ...   ...     ...  ..       ...
117  13.40  2.59  Yes   Mon  Dinner   3  0.193284
118  45.17  9.46  Yes   Tue   Lunch   1  0.209431
119  29.27  9.59   No   Sat  Dinner   5  0.327639
120  41.33  9.23   No   Sun   Lunch   1  0.223324
121  45.32  4.33   No   Mon  Dinner   2  0.095543

[122 rows x 7 columns]

In [7]:
df1.sort_values(by='小費比例',ascending=False).iloc[:10]

       總票價    小費  吸煙者    日期      時間  人數      小費比例
32    7.93  9.87   No  Thur  Dinner   4  1.244641
98    6.14  6.92   No  Thur   Lunch   2  1.127036
56    8.98  9.43  Yes   Fri  Dinner   4  1.050111
77    8.33  8.02   No   Sat  Dinner   2  0.962785
37    9.40  7.55  Yes  Thur  Dinner   3  0.803191
72    5.25  4.05   No   Fri  Dinner   4  0.771429
5    12.02  8.75   No   Tue  Dinner   2  0.727953
4    12.02  8.36  Yes   Fri  Dinner   2  0.695507
90   10.38  6.87   No   Tue   Lunch   5  0.661850
109   8.46  5.52  Yes  Thur   Lunch   1  0.652482

In [10]:
def top(df,n=5,column='小費比例'):
    return df1.sort_values(by='小費比例',ascending=False).iloc[:n]

top(df1,n=10)

       總票價    小費  吸煙者    日期      時間  人數      小費比例
32    7.93  9.87   No  Thur  Dinner   4  1.244641
98    6.14  6.92   No  Thur   Lunch   2  1.127036
56    8.98  9.43  Yes   Fri  Dinner   4  1.050111
77    8.33  8.02   No   Sat  Dinner   2  0.962785
37    9.40  7.55  Yes  Thur  Dinner   3  0.803191
72    5.25  4.05   No   Fri  Dinner   4  0.771429
5    12.02  8.75   No   Tue  Dinner   2  0.727953
4    12.02  8.36  Yes   Fri  Dinner   2  0.695507
90   10.38  6.87   No   Tue   Lunch   5  0.661850
109   8.46  5.52  Yes  Thur   Lunch   1  0.652482

In [13]:
df1.groupby('吸煙者').apply(top,n=5,include_groups=False)

         總票價    小費  吸煙者    日期      時間  人數      小費比例
吸煙者
No  32  7.93  9.87   No  Thur  Dinner   4  1.244641
    98  6.14  6.92   No  Thur   Lunch   2  1.127036
    56  8.98  9.43  Yes   Fri  Dinner   4  1.050111
    77  8.33  8.02   No   Sat  Dinner   2  0.962785
    37  9.40  7.55  Yes  Thur  Dinner   3  0.803191
Yes 32  7.93  9.87   No  Thur  Dinner   4  1.244641
    98  6.14  6.92   No  Thur   Lunch   2  1.127036
    56  8.98  9.43  Yes   Fri  Dinner   4  1.050111
    77  8.33  8.02   No   Sat  Dinner   2  0.962785
    37  9.40  7.55  Yes  Thur  Dinner   3  0.803191