In [17]:
import pandas as pd

df1= pd.read_csv('各鄉鎮市區人口密度.csv')

print(type(df1.columns ))

#轉成list並顯示
col_list= df1.columns.tolist()
print(col_list)

<class 'pandas.core.indexes.base.Index'>
['\ufeffstatistic_yyy', 'site_id', 'people_total', 'area', 'population_density']

In [18]:
df1

     ﻿statistic_yyy site_id people_total     area population_density
0               113  新北市板橋區       553538  23.1373              23924
1               113  新北市三重區       383355  16.3170              23494
2               113  新北市中和區       405956  20.1440              20153
3               113  新北市永和區       213742   5.7138              37408
4               113  新北市新莊區       423503  19.7383              21456
..              ...     ...          ...      ...                ...
365             113  連江縣北竿鄉         3062   9.9000                309
366             113  連江縣莒光鄉         1518   4.7000                323
367             113  連江縣東引鄉         1555   3.8000                409
368             113    東沙群島            …   2.3800                  …
369             113    南沙群島            …   0.5045                  …

[370 rows x 5 columns]

In [ ]:
#更改df的欄位名稱
#使用已存在的cols列表重新命名欄位
df1.columns= df1.loc[0].tolist()
df2=df1.drop(index=0).reset_index(drop=True)
#顯示前10筆資料
df2.head(10)
#修改欄位名稱
df2.columns = ['統計年','鄉鎮市區','人口數','面積(平方公里)','人口密度(人/平方公里)']
df2.head(10)

   統計年    鄉鎮市區     人口數  面積(平方公里) 人口密度(人/平方公里)
0  113  新北市三重區  383355   16.3170        23494
1  113  新北市中和區  405956   20.1440        20153
2  113  新北市永和區  213742    5.7138        37408
3  113  新北市新莊區  423503   19.7383        21456
4  113  新北市新店區  306571  120.2255         2550
5  113  新北市樹林區  178981   33.1288         5403
6  113  新北市鶯歌區   89339   21.1248         4229
7  113  新北市三峽區  115335  191.4508          602
8  113  新北市淡水區  200726   70.6565         2841
9  113  新北市汐止區  210817   71.2354         2959