In [10]:
import pandas as pd

series1 = pd.Series([10, 20, 30, 40, 50], index=['a', 'c', 'e', 'd', 'b'])


seriese2 = series1.sort_index()
series1.reindex(sorted(series1.index))
series1.reindex(['a', 'b', 'c', 'd', 'e'])
series1.reindex(['c','d','e'])

c    20
d    40
e    30
dtype: int64

In [18]:
import numpy as np

frame = pd.DataFrame(
    data=np.arange(9).reshape(3, 3)
    ,index=['a', 'c', 'e']
    ,columns=['Ohio', 'Texas', 'California']    
    )

frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
e     6      7           8

In [22]:
frame.reindex(sorted(frame.index))
frame.reindex(index=['a', 'c'],columns=['California', 'Ohio'])

   California  Ohio
a           2     0
c           5     3

In [ ]:
# 實體方法dropna()，可以用來移除缺失值

frame1= pd.DataFrame(
    data=np.arange(16).reshape(4, 4)
    ,index=['台北', '台中', '台南', '高雄']
    ,columns=['one', 'two', 'three', 'four']    
    )
frame1

    one  two  three  four
台北    0    1      2     3
台中    4    5      6     7
台南    8    9     10    11
高雄   12   13     14    15

In [27]:
frame1.drop(index=['台北','台中'],columns=['one','two'])

    three  four
台南     10    11
高雄     14    15